### ISSUE TITLE
"Fail on skip-ci" workflow step always fails on master.

### ISSUE THREAD

**Issue by dumol** [chevah/compat#109]
Ditto, e.g. https://github.com/chevah/compat/runs/2256419632. 

But also the corresponding jobs for a few mare previous commits in master.

**Comment by adiroiban** [comment]
Thanks for the report

I can fix it as part of #104 .... in 98dce23

The problem is that Windows is missing the `if`

```
    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'
```
